// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB123FsYcRUJBi5Y1wG5trTwWhgT2Qvntw',
    appId: '1:42087615644:web:9343fa9ca6b997f5187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    authDomain: 'auth-firebase-7a66e.firebaseapp.com',
    databaseURL: 'https://auth-firebase-7a66e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHFIwnf7BO59QglVFmmrBauJko4bUi0E',
    appId: '1:42087615644:android:4cb4a130e6c84bf4187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    databaseURL: 'https://auth-firebase-7a66e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATOFGDXncZbHMCRE-Jr3ObF2laNvPkW4',
    appId: '1:42087615644:ios:47238d1de54b438b187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    databaseURL: 'https://auth-firebase-7a66e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
    androidClientId: '42087615644-i12n9mmheu0htipid7tt05unjmhbcnbj.apps.googleusercontent.com',
    iosClientId: '42087615644-b6t8fa2ijpae8mc9jj81rhdvjru8ep2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAATOFGDXncZbHMCRE-Jr3ObF2laNvPkW4',
    appId: '1:42087615644:ios:47238d1de54b438b187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    databaseURL:
        'https://auth-firebase-7a66e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
    androidClientId:
        '42087615644-i12n9mmheu0htipid7tt05unjmhbcnbj.apps.googleusercontent.com',
    iosClientId:
        '42087615644-b6t8fa2ijpae8mc9jj81rhdvjru8ep2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB123FsYcRUJBi5Y1wG5trTwWhgT2Qvntw',
    appId: '1:42087615644:web:1fd42f3306910c99187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    authDomain: 'auth-firebase-7a66e.firebaseapp.com',
    databaseURL: 'https://auth-firebase-7a66e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
  );

}