// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB123FsYcRUJBi5Y1wG5trTwWhgT2Qvntw',
    appId: '1:42087615644:web:aad714c7ad2900c7187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    authDomain: 'auth-firebase-7a66e.firebaseapp.com',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHFIwnf7BO59QglVFmmrBauJko4bUi0E',
    appId: '1:42087615644:android:093294ff5139c56c187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATOFGDXncZbHMCRE-Jr3ObF2laNvPkW4',
    appId: '1:42087615644:ios:b7b7c51b2f324f6a187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAATOFGDXncZbHMCRE-Jr3ObF2laNvPkW4',
    appId: '1:42087615644:ios:b7b7c51b2f324f6a187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB123FsYcRUJBi5Y1wG5trTwWhgT2Qvntw',
    appId: '1:42087615644:web:6b125db465030720187159',
    messagingSenderId: '42087615644',
    projectId: 'auth-firebase-7a66e',
    authDomain: 'auth-firebase-7a66e.firebaseapp.com',
    storageBucket: 'auth-firebase-7a66e.firebasestorage.app',
  );
}
