// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDItRAntlKUUCutEiR1zlG4iQEVHFgq7nk',
    appId: '1:491122931834:web:2c460bd28675a706efe3c3',
    messagingSenderId: '491122931834',
    projectId: 'smarthome-e30cf',
    authDomain: 'smarthome-e30cf.firebaseapp.com',
    storageBucket: 'smarthome-e30cf.firebasestorage.app',
    measurementId: 'G-0VRFXWGXLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CJgcxfQ-a6p6xneDyOy8RwZGuAOLPKg',
    appId: '1:491122931834:android:f7eb79069a70afd6efe3c3',
    messagingSenderId: '491122931834',
    projectId: 'smarthome-e30cf',
    storageBucket: 'smarthome-e30cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIE62UatDYjz8EaaVsTz9-ZQKZt7G0Zk4',
    appId: '1:491122931834:ios:b4b720f1c9a17e37efe3c3',
    messagingSenderId: '491122931834',
    projectId: 'smarthome-e30cf',
    storageBucket: 'smarthome-e30cf.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIE62UatDYjz8EaaVsTz9-ZQKZt7G0Zk4',
    appId: '1:491122931834:ios:b4b720f1c9a17e37efe3c3',
    messagingSenderId: '491122931834',
    projectId: 'smarthome-e30cf',
    storageBucket: 'smarthome-e30cf.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDItRAntlKUUCutEiR1zlG4iQEVHFgq7nk',
    appId: '1:491122931834:web:f1f8bf3dbbfd0ba8efe3c3',
    messagingSenderId: '491122931834',
    projectId: 'smarthome-e30cf',
    authDomain: 'smarthome-e30cf.firebaseapp.com',
    storageBucket: 'smarthome-e30cf.firebasestorage.app',
    measurementId: 'G-MYM8YVH212',
  );
}
